/* Auto-generated by AuthSystem - 2026-02-28T19:10:03.299Z */
// Public configuration for auth forms
// These values are embedded at build time
// The forms call the public API (Netlify Functions), not Supabase directly

export const config = {
  apiBaseUrl: '/api', // Uses Netlify redirect from netlify.toml
  appId: 'app_804b6704-24a',
  apiKey: 'ak_production_ba952a1d31481afac0510cffd42c80ea'
};
