<<<<<<< HEAD
import { useState } from 'react';
import { BrowserRouter, Routes, Route, Navigate } from 'react-router-dom';
import { AuthProvider, useAuth } from './contexts/AuthContext';
import { ToastProvider } from './contexts/ToastContext';
import { DialerProvider } from './contexts/DialerContext';
import { NavigationProvider, useNavigation } from './contexts/NavigationContext';
import { LoginForm } from './components/Auth/LoginForm';
import { CallbackHandler } from './components/Auth/CallbackHandler';
import { Sidebar } from './components/Layout/Sidebar';
import { PhoneDialer } from './components/Common/PhoneDialer';
import { IncomingCallNotification } from './components/Common/IncomingCallNotification';
import { CallModal } from './components/Common/CallModal';
import { DashboardModule } from './components/Dashboard/DashboardModule';
import { ClientsModule } from './components/Clients/ClientsModule';
import { CampaignsModule } from './components/Campaigns/CampaignsModule';
import { CallsModule } from './components/Calls/CallsModule';
import { TicketsModule } from './components/Tickets/TicketsModule';
import { InboxModule } from './components/Inbox/InboxModule';
import { SettingsModule } from './components/Settings/SettingsModule';
import ParametersModule from './components/Settings/ParametersModule';
import { WebChatModule } from './components/WebChat/WebChatModule';
import { useTwilioDevice } from './hooks/useTwilioDevice';
import { useInvoiceAutoValidation } from './hooks/useInvoiceAutoValidation';
import { useInvoiceEmailQueue } from './hooks/useInvoiceEmailQueue';
import { useInvoicePdfQueue } from './hooks/useInvoicePdfQueue';
=======
/* Auto-generated by AuthSystem - 2026-02-28T19:10:03.299Z */
import React from 'react';
import { Routes, Route, Navigate, useSearchParams, useLocation } from 'react-router-dom';
import { config } from './lib/config';
import PublicAuthRouter from './components/auth/PublicAuthRouter';
>>>>>>> 1fc69288a705a8e899209b39b0d85c38efb73181

export default function App() {
  const [searchParams] = useSearchParams();
  const location = useLocation();

  const appId = searchParams.get('app_id') || config.appId || '';

  // Map path to form type
  const getFormType = (): 'login' | 'register' | 'reset-password' => {
    if (location.pathname.includes('register')) return 'register';
    if (location.pathname.includes('reset')) return 'reset-password';
    return 'login';
  };

  if (!appId) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="bg-white p-8 rounded-lg shadow-lg max-w-md">
          <h1 className="text-2xl font-bold text-gray-900 mb-4">Error de Configuración</h1>
          <p className="text-gray-600 mb-4">
            El parámetro <code className="bg-gray-100 px-2 py-1 rounded">app_id</code> es requerido en la URL.
          </p>
          <p className="text-sm text-gray-500">
            Ejemplo: <code className="bg-gray-100 px-2 py-1 rounded text-xs">
              /login?app_id=xxx
            </code>
          </p>
        </div>
      </div>
    );
  }

<<<<<<< HEAD
  if (!isAuthenticated) {
    return <Navigate to="/login" replace />;
  }

  return <>{children}</>;
}

function MainApp() {
  const { activeModule, setActiveModule } = useNavigation();
  const [incomingCallModalOpen, setIncomingCallModalOpen] = useState(false);
  const [currentIncomingCall, setCurrentIncomingCall] = useState<any>(null);
  const { isReady, device, activeCall, makeCall } = useTwilioDevice();

  useInvoiceAutoValidation();
  // useInvoiceEmailQueue(); // DESHABILITADO: Usamos API externa generate-pdf que envía emails
  useInvoicePdfQueue();


  const handleAcceptIncomingCall = (call: any) => {
    setCurrentIncomingCall(call);
    setIncomingCallModalOpen(true);
  };

  const renderModule = () => {
    switch (activeModule) {
      case 'dashboard':
        return <DashboardModule />;
      case 'clients':
        return <ClientsModule />;
      case 'campaigns':
        return <CampaignsModule />;
      case 'calls':
        return <CallsModule />;
      case 'tickets':
        return <TicketsModule />;
      case 'inbox':
        return <InboxModule />;
      case 'webchat':
        return <WebChatModule />;
      case 'settings':
        return <SettingsModule />;
      case 'parameters':
        return <ParametersModule />;
      default:
        return <DashboardModule />;
    }
  };

=======
>>>>>>> 1fc69288a705a8e899209b39b0d85c38efb73181
  return (
    <Routes>
      <Route
        path="/login"
        element={
          <PublicAuthRouter
            appId={appId}
            formType="login"
          />
        }
      />
      <Route
        path="/register"
        element={
          <PublicAuthRouter
            appId={appId}
            formType="register"
          />
        }
      />
      <Route
        path="/reset-password"
        element={
          <PublicAuthRouter
            appId={appId}
            formType="reset-password"
          />
        }
      />
      <Route path="/" element={<Navigate to="/login" replace />} />
      <Route path="*" element={<Navigate to="/login" replace />} />
    </Routes>
  );
}
